# Generated by Django 2.1.1 on 2019-01-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190113_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='agenda_slug',
            field=models.CharField(default='downtown_vi', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
